export const REQUEST_JOBS = 'REQUEST_JOBS';
export const SUCCESS_JOBS = 'SUCCESS_JOBS';
export const FAIL_JOBS = 'FAIL_JOBS';

export const REQUEST_FILTERS = 'REQUEST_FILTERS';
export const SUCCESS_FILTERS = 'SUCCESS_FILTERS';
export const FAIL_FILTERS = 'FAIL_FILTERS';

export const ALTER_QUERY_FILTER = 'ALTER_QUERY_FILTER';
export const ALTER_QUERY_SORTER = 'ALTER_QUERY_SORTER';
